name: healix
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.2.0
  http: ^1.2.1
  url_launcher: ^6.1.12
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  local_auth: ^2.2.0
  image_picker: ^1.1.2
  web_socket_channel: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1   # âœ… Add this here

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/download.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/healixicon.png"
  min_sdk_android: 21
  
